---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mutiapps-deployment
  namespace: argocd
  # force argocd to delete the k8s app first and then removes it from argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/durga61/argocd-tutorial.git
    targetRevision: HEAD
    path: environment/staging/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true